require 'yaml'
dir = File.join(File.dirname(File.expand_path(__FILE__)))
settings = YAML.load_file("#{dir}/settings.yaml")

Vagrant.require_version ">= 2.0.0"
Vagrant.configure("2") do |config|
  config.vm.define settings[:machine][:hostname]

  # https://app.vagrantup.com/bento/boxes/ubuntu-18.04
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
    vb.cpus = 1
    vb.name   = settings[:machine][:hostname]
    vb.memory = settings[:machine][:memory]
  end

  # vagrant@ubuntu-18-04
  config.vm.hostname = settings[:machine][:hostname]

  # Synchronize folder
  #config.vm.synced_folder settings[:synced_folder][:host], #settings[:synced_folder][:guest], owner: "vagrant", group: "vagrant"

  # Copy files from host machine
  config.vm.provision :file, source: "C:/\Users/\iec_000/\Test/\hostfile_test.txt", destination: "/home/vagrant/hostfile_test.txt"

  # Provision bash script
  config.vm.provision :shell, path: "provision.sh", env: {
    #"GUEST_SYNCED_FOLDER" => settings[:synced_folder][:guest],
    "TIMEZONE"            => settings[:machine][:timezone]
  }
end
